sudo: required
language: python
cache: pip
python:
- '2.7'
- '3.5'
services:
- redis-server
install:
- pip install lxml
- pip install coveralls
script:
- coverage run setup.py test
after_success:
- coverage combine
- coveralls
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: DaVinciDW
  password:
    secure: ALKkeMxica0KEUM+eVxKA4BG7OitmBdmoZc6CLr29fB+pQePjdH4HU9To3ddmsTcMBj+Ac9UTKOVstzBFOSnBDOWCDSXVMVRyShBSsidcSHgeSznJvqOW+7uvnN8+YouD5uU8fhA7+WBlhOvqWMCy7xsWfUCjpS8TF/+UK8TgsZUGZ/ab2lvkty8Vy67z5FPokcRHVyysH8QPH3c5NuHx6X7zwJjJcrFFvrp6yswcdkqzJPemRPsEF+NVv4/v5MUPtDBJbkIQ43rZl0IzP88WvACg7xOtMhcijX6KTXPgmq8VI/piA6QmEDBKp9C+YY1XImC8Y+C4mnxFSTYvXmpfs1jZoflyKR7ZaIpQS2/F9gSBF/fjpov0N+wqWeKtBdmMyHSQaDYt8t/5EPb4RGVnPxe52YNGmfSXoD56R/OTp9IAUsIfNU9UBkFuOSISueUGmV8Ajb3aiQFc2MVSbqM4hDdDlC8eqR1K3acotKYb1vEzsBP7a45L3lmk5RjzVIu9fRqfrNSkE6gU/GFEsXgbLX2AizbHXFUVmHUBqBX9jHqC9q0OgV9cQvWVYHHJaYcfiSnbUGU+iXCzmZ+9RZnpX3Eya7hFsnEifTY0DIbqxnm2QZjW9pX0AwE2BMx51wx2lXMu9Q6sZU3BRipQQsxK45KeOB/JwwsMXcm3sT3FGM=
  on:
    branch: master
    tags: false
    repo: DarkSand/fetchman
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
